### ISSUE TITLE
OAI dataset

### ISSUE THREAD

**Issue by ghost** [MIPT-Oulu/JS2#1]
I have requested to access data in the Osteoarthritis Initiative but it takes 2 months from now the website is still not working
can you please share the dataset?

**Comment by tommyngx** [comment]
Please help with the dataset, I can't anywhere even the website due to the end of funding. Please assist if you can!

**Comment by soupault** [comment]
Hi @hammadyounas2008 and @Tommy-Ngx! The OAI has moved to https://nda.nih.gov/oai/ . You should be able to request the access and download the images from there. We are not able to redistribute the data due to the OAI data agreement terms.
